### ISSUE TITLE
Questions about the evaluate of datasets

### ISSUE THREAD

**Issue by Sugar55888** [cvg/nerf-on-the-go#1]
Hi, thank you for your excellent work! Regarding the evaluation of the nerf-on-the-go dataset, I have some doubts. Because some of the test images contain occlusions, and the in the wild method focuses on removing the distractors and rendering clean images. Will this lead to a decrease in the PSNR value calculated between the rendered image and the test true value image? I don't know if my idea is right. Could you provide some suggestions?

**Comment by rwn17** [comment]
Could you please list the index for the test images with occlusion? You are right the test set should be distractor-free.

**Comment by Sugar55888** [comment]
@rwn17 Hi, in some highly occluded scenes, such as train_station, almost every picture has distractors. It's hard to select some images for test. 
![image](https://github.com/user-attachments/assets/31b7e8d2-7d2e-4f98-b345-4cbde1e607c8)

**Comment by rwn17** [comment]
Yes you are correct, so we do not include this scene in the quantitative evaluation. Please refer to Table 1 for the scenes we use for quantitative assessment.

**Comment by Sugar55888** [comment]
@Thanks for your answer! I have seen it!
